### ISSUE TITLE
[Bug] Won't run on Linux Mint 20.2 Cinnamon (missing dependencies??)

### ISSUE THREAD

**Issue by forever-and-a-day** [e-k1/rmm2#2]
when attempting to run rmm2 (from usr/bin), it doesn't launch and prints the following in the terminal:
```
rmm2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by rmm2)
rmm2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by rmm2)
```
`glibc`, `GLIBC_2.33`, `glibc_2.33`, etc do not appear to be installable packages (via apt at least).  `glibc-source` and `glibc-doc-reference` do appear in the official software repositories, but from their description and package name, I don't think either are what I'm looking for.  

Tried reproducing in a stock live VM of Linux Mint, same story :/

Not sure if this is a bug or if rmm2 isn't compatible with my distribution, but considering Mint is based off of fairly recent Ubuntu it seems unlikely...

**Comment by kankkueo** [comment]
I updated the binary to a version compiled using mint and it seems to be working. If it doesn't, you should try building it yourself.
